VyHung/VyHung/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('ckeditor/',include('ckeditor_uploader.urls')),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name="password_reset"),
    #Where can I find OR set theses paths these values
    #2
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name="email_sent.html"),name="password_reset_done"),
    #3
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"), name="password_reset_confirm"),


    #4
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_complete.html"), name="password_reset_complete"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

VyHung/base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('posts/', views.posts, name='posts'),
    path('post/<slug:slug>/', views.post, name='post'),
    path('postLike/<slug:slug>/', views.postLike, name='postLike'),
    path('postLikeIndex/<slug:slug>/', views.postLikeIndex, name='postLikeIndex'), #Like Index
    path('LikeThisPost/<slug:slug>/', views.LikeThisPost, name='LikeThisPost'), #Like this post
    path('profile/', views.profile, name='profile'),
    path('create_post/', views.createPost, name='create_post'),
    path('update_post/<slug:slug>/', views.updatePost, name='update_post'),
    path('delete_post/<slug:slug>/', views.deletePost, name='delete_post'),
    path('send_email/', views.sendEmail, name='send_email'),

    path('login/', views.loginPage, name="login"),
	path('register/', views.registerPage, name="register"),
	path('logout/', views.logoutUser, name="logout"),

	path('account/', views.userAccount, name="account"),
	path('update_profile/', views.updateProfile, name="update_profile"),
]

VyHung/base/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_save
from django.contrib.auth.models import User
from django.dispatch import receiver

    
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys

# Create your models here.
# from gdstorage.storage import GoogleDriveStorage

# Define Google Drive Storage
# gd_storage = GoogleDriveStorage()

class Profile(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200, blank=True, null=True)
    last_name = models.CharField(max_length=200, blank=True, null=True)
    email = models.CharField(max_length=200)
    profile_pic = models.ImageField(upload_to="profile", default="images/user.jpg")
    bio = models.TextField(null=True, blank=True)
    Facebook = models.CharField(max_length=200,null=True, blank=True)

    def __str__(self):
        name = str(self.first_name)
        if self.last_name:
            name += ' ' + str(self.last_name)
        return name

    def save(self, *args, **kwargs):
        check = False
        if self.profile_pic:

            imageTemproary = Image.open(self.profile_pic)
            if imageTemproary.mode != 'RGB':
                imageTemproary = imageTemproary.convert('RGB')
            # print("_____",imageTemproary.size[0],imageTemproary.format)
            if imageTemproary.size[0] > 700  or imageTemproary.format != 'JPEG':
                outputIoStream = BytesIO()
                imageTemproaryResized = imageTemproary
                imageTemproaryResized.thumbnail((700, 700),
                                                Image.ANTIALIAS)
                imageTemproaryResized.save(outputIoStream, format='JPEG', quality=65)
                outputIoStream.seek(0)
                self.profile_pic = InMemoryUploadedFile(outputIoStream, 'ImageField',
                                                        "%s.jpg" % self.profile_pic.name.split('.')[0], 'image/jpeg',
                                                        sys.getsizeof(outputIoStream), None)
                check = True
                super(Profile, self).save(*args, **kwargs)
        if(check == False):
            super(Profile, self).save(*args, **kwargs)

    


class Tag(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    

class Post(models.Model):
    headline = models.CharField(max_length=200)
    sub_headline  = models.CharField(max_length=200,null = True, blank=True)
    thumbnail = models.ImageField(null = True, blank=True,upload_to="posts",default="images/x.jpg")
    body  = RichTextUploadingField(null = True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    # active = models.BooleanField(default=False)
    # features = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    tags = models.ManyToManyField(Tag)
    likes = models.ManyToManyField(User,blank=True,related_name='post_likes')
    slug = models.SlugField(null=True, blank=True)
    
    def number_of_likes(self):
        return self.likes.count()
    
    def __str__(self):
        return self.headline
    
    def save(self, *args, **kwargs):

        if self.slug == None:
            slug = slugify(self.headline)

            has_slug = Post.objects.filter(slug=slug).exists()
            count = 1
            while has_slug:
                count += 1
                slug = slugify(self.headline) + '-' + str(count) 
                has_slug = Post.objects.filter(slug=slug).exists()

            self.slug = slug

        # super().save(*args, **kwargs)

        if self.thumbnail:

            imageTemproary = Image.open(self.thumbnail)
            if imageTemproary.mode != 'RGB':
                imageTemproary = imageTemproary.convert('RGB')
            if imageTemproary.size[0] != 900  or imageTemproary.format != 'JPEG':
                outputIoStream = BytesIO()
                imageTemproaryResized = imageTemproary
                imageTemproaryResized.thumbnail((900,(self.thumbnail.height)/(self.thumbnail.width)*900), Image.ANTIALIAS)
                imageTemproaryResized.save(outputIoStream , format='JPEG', quality=75)
                outputIoStream.seek(0)
                self.thumbnail = InMemoryUploadedFile(outputIoStream,'ImageField', "%s.jpg" %self.thumbnail.name.split('.')[0], 'image/jpeg', sys.getsizeof(outputIoStream), None)
            
                super(Post, self).save(*args, **kwargs)

    @property
    def created_dynamic(self):
        now = timezone.now()
        return now
    



class favorite(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class song(models.Model):
    song = models.CharField(max_length=20)

    def __str__(self):
        return self.song
    
class images(models.Model):
    title = models.CharField(max_length=10,null=True)
    image = models.ImageField(blank=True, null=True,upload_to="slides",default="/images/x.jpg")

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.image:

            imageTemproary = Image.open(self.image)
            if imageTemproary.mode != 'RGB':
                imageTemproary = imageTemproary.convert('RGB')
            if imageTemproary.size[0] != 550  or imageTemproary.format != 'JPEG':
                outputIoStream = BytesIO()
                imageTemproaryResized = imageTemproary
                imageTemproaryResized.thumbnail((550, (self.image.height)/(self.image.width)*550), Image.ANTIALIAS)
                imageTemproaryResized.save(outputIoStream, format='JPEG', quality=70)
                outputIoStream.seek(0)
                self.image = InMemoryUploadedFile(outputIoStream, 'ImageField', "%s.jpg" % self.image.name.split('.')[0],
                                                'image/jpeg', sys.getsizeof(outputIoStream), None)
                super(images, self).save(*args, **kwargs)


class Music(models.Model):
    music = models.CharField(max_length=100)
    def __str__(self):
        return self.music

class AboutMe(models.Model):
    maxim = models.CharField(max_length=100)
    more_about_me_1 = models.CharField(max_length=200)
    more_about_me_2 =  models.CharField(max_length=200,null = True, blank=True)
    images_slide = models.ManyToManyField(images)
    image_author = models.ImageField(upload_to="author",default="/images/x.jpg")
    headline_favorite = models.CharField(max_length=200,null = True, blank=True)
    favorites =  models.ManyToManyField(favorite)
    songs = models.ManyToManyField(song)
    
    def __str__(self):
        return self.maxim

    def save(self, *args, **kwargs):

        if self.image_author:
            imageTemproary = Image.open(self.image_author)
            if imageTemproary.mode != 'RGB':
                imageTemproary = imageTemproary.convert('RGB')
            if imageTemproary.size[0] != 600  or imageTemproary.format != 'JPEG':
                outputIoStream = BytesIO()
                imageTemproaryResized = imageTemproary
                imageTemproaryResized.thumbnail((600 , (self.image_author.height)/(self.image_author.width)*600),
                                                Image.ANTIALIAS)
                imageTemproaryResized.save(outputIoStream, format='JPEG', quality=80)
                outputIoStream.seek(0)
                self.image_author = InMemoryUploadedFile(outputIoStream, 'ImageField',
                                                        "%s.jpg" % self.image_author.name.split('.')[0], 'image/jpeg',
                                                        sys.getsizeof(outputIoStream), None)
                super(AboutMe, self).save(*args, **kwargs)


class PostComment(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True  )
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, blank=True )
    body = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    post_comment = models.CharField(max_length=200,null = True, blank=True) # xac dinh tham chieu toi xem ai cmt
    def __str__(self):
        return self.body
    

    @property
    def created_dynamic(self):
        now = timezone.now()
        return now
    




    





	
    

VyHung/base/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Post, Profile


class CustomUserCreationForm(UserCreationForm):
    
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'email', 'password1', 'password2']
	def clean_email(self):
		email = self.cleaned_data.get('email')
		
		if email =='':
			raise forms.ValidationError("Email cannot be empty or null !")
		if User.objects.filter(email=email).exists():
			raise forms.ValidationError("email was already registered !")
		return email

		
		


class PostForm(ModelForm):

	class Meta:
		model = Post
		# fields = '__all__'
		fields = ['headline', 'sub_headline', 'thumbnail', 'body', 'tags']
		widgets = {
			'tags':forms.CheckboxSelectMultiple(),
		}

class UserForm(ModelForm):
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'email']
	

class ProfileForm(ModelForm):
	class Meta:
		model = Profile
		fields = '__all__'
		#fields = ['first_name','last_name','profile_pic','bio','Facebook']
		exclude = ['user']

VyHung/base/templates/base/delete.html
{% extends 'base/main.html' %}

{% block content %}
    <div class="main-container">
	<a class="btn btn-sm btn-primary" href="{% url 'posts' %}">&laquo Back to Posts</a>
	
        <form action="" method="POST" >
            {% csrf_token %}
            <p>Bạn chắc chắn muốn xóa bài viết</p>

            <input class="btn btn-danger" type="submit" value="Xác nhận xóa">
            
        </form>
    </div>
{% endblock content %}

VyHung/base/templates/base/email_sent.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}

<style type="text/css">
	html, body{
		height: 100%;
		
	}

	#page-wrapper{
		height: 100%;
		display: flex;
		justify-content: center;
		align-items: center;
		text-align: center;
		background-color: #eaeaea;
		background-image: var(--background-image);
	}

	#success-box{
		max-width: 800px;
		height: auto;
		background-color: #fff;
		border:1px solid #888;
		border-radius: 5px;
		padding: 15px;
		background-image: var(--background-image);
		box-shadow: 0 2px 4px 0 var(--color-box-shadow);
	}

	#success-box p{
		font-size: 18px;
	}
	.btn-color{
		background-image: var(--background-image);
		box-shadow: 0 2px 4px 0 var(--color-box-shadow);
	}

</style>

<div id="page-wrapper">
	<div id="success-box" class="content-block">
		<h1>Thanks for reaching out!</h1>
		<p>Your message was successfully sent.</p>
		<a id="back-btn" class="btn btn-success btn-color" href="{% url 'home' %}">BACK TO HOME</a>
	</div>
</div>

{% endblock content %}

VyHung/base/templates/base/email_template.html
{{message}}

{{name}}

{{email}}

VyHung/base/templates/base/login.html
{% include 'base/main.html' %}
{% load static %}

{% block content %}

<section id="login-page-wrapper">
	<div id="login-form-wrapper">
		{% if messages %}
			{% for message in messages %}
				{% if message.tags == 'success' %}
					<div class="alert alert-success" role="alert">
						<span>{{message}}</span>					
					</div>
				{% elif message.tags == 'error' %}
					<div class="alert alert-danger" role="alert">
						<span>{{message}}</span>					
					</div>
				{% endif %}
			{% endfor %}
		{% endif %}

		<h3 style="text-align: center">Member Login</h3>
		<hr>
		<form method="POST">
			{% csrf_token %}
			<label>Email</label>
			<input class="form-control" type="email" name="email">
			<br>
			<label>Password</label>
			<input class="form-control" type="password" name="password">
			<br>
			<input class="btn btn-primary btn-lg btn-block" type="submit" value="Login">
		</form>

		<br>
		<p>Dont have an account? <a href="{% url 'register' %}">Register</a></p>
		<p>Forgot your password? <a href="{% url 'password_reset' %}">Reset</a></p>
	</div>
</section>

{% endblock content %}

VyHung/base/templates/base/main.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<title>My Story</title>
	<meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1"/>

	<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
	<link id="theme-style" rel="stylesheet" type="text/css" href="">
	<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">
	   
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"> 
	<link href="https://use.fontawesome.com/releases/v5.0.4/css/all.css" rel="stylesheet">  

	
	
</head>
<body>
    {% include 'base/navbar.html' %}
    {% block content %}
            <!--    Content -->
    {% endblock content %}
   <script type="text/javascript">
		let static = "{% static 'css' %}"
	</script>

<body onmousemove=/HideMenu()/ oncontextmenu="return false" ondragstart="return false" onselectstart ="return false" onselect="document.selection.empty()" oncopy="document.selection.empty()" onbeforecopy="return false" onmouseup="document.selection.empty()">


	<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script> 
	{% comment %} <script type="text/javascript" src="{% static 'js/main.js' %}"></script> {% endcomment %}

</body>
</html>

VyHung/base/templates/base/navbar.html
<nav class="navbar navbar-expand-md navbar-light sticky-top">
	<div class="container-fluid">
		<a class="navbar-branch" href="{% url 'home'  %}">
			<img src="" height="50">
		</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" 
			data-target="#navbarResponsive">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item">
					<a class="nav-link active" href="{% url 'home'  %}">Home</a>
				</li>
				
				<li class="nav-item">
					<a class="nav-link" href="{% url 'posts'  %}">Posts</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'home'  %}#About">About</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'home'  %}#Contact">Contact</a>
				</li>
			
				{% if request.user.is_authenticated %}
					<li  class="nav-item">
					<a class="nav-link" href="{% url 'account' %}"> Account</a>
					</li>
					<li class="nav-link"  class="nav-item">
					<a href="{% url 'logout' %}">Logout</a>
					</li>
				{% else %}
					<li class="nav-link"  class="nav-item">
					<a href="{% url 'login' %}">Login</a>
					</li>
				{% endif %}
			</ul>

			

		</div>
	</div>
</nav>

VyHung/base/templates/base/password_reset.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


<div class="main-container">
	<h3>Password reset</h3>

	<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>


	<form method="POST" action="">
		{% csrf_token %}
		{{form|crispy}}
		<br>
		<input class="btn btn-primary" type="submit" value="Reset my password">
	</form>
</div>

{% endblock content %}

VyHung/base/templates/base/post.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}

<style type="text/css">
	body{
		background-image: var(--background-image);
	}
	img{
		max-width: 100%;
		object-fit: cover;
	}

	.featured_image{
		margin-top: 20px;
		margin-bottom: 20px;
	}

	.post-container{
			width: 900px;
			margin: 0 auto;
			padding-top: 20px;
			padding-bottom: 20px;
	}

	.comments-wrapper{
		margin-top: 50px;
		padding: 10px;
		border:1px solid var(--borderColor);
		-webkit-box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
		-moz-box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
		box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
	}

	.comment{
		display: flex;
		padding: 15px;
	}

	.comment-author{
		font-size: 14px;
		font-weight: 700;
		color: rgb(30, 174, 219) !important;
		margin-top: 8px;
	}

	.author-pic{
		width: 50px;
		height: 50px;
		border-radius: 50% !important;
		margin-right: 10px;
	}

	.comment-body{
		word-break: break-word;
		font-size: 16px;

}

	.comment-span{
		background-image: var(--navColor );
		box-shadow: 0 2px 4px 0 var(--color-box-shadow);
		border-radius: 5px;
		margin : 5px;
		padding: 8px;
}
	@media screen and (max-width: 900px){
		.post-container{
			width: 95%;
			flex-direction: column;
		}
	}

	@media screen and (max-width: 1130px)
	.post-container {
		width: 98%;
		flex-direction: column;
	}

</style>

<div class="post-container">

	<a class="btn btn-sm btn-primary" href="{% url 'posts' %}">&laquo Back to Posts</a>

	{% if request.user.is_staff %}
		 <a class="btn btn-sm btn-primary" href="{% url 'update_post' post.slug %}">Edit</a>
		 <a class="btn btn-sm btn-danger" href="{% url 'delete_post' post.slug %}">Delete</a>
	{% endif %}

	<img class="featured_image" src="{{post.thumbnail.url}}">

	{% for tag in post.tags.all %}
		<span class="tag">{{tag}}</span>
	{% endfor %}
	<hr>

	<h1>{{post.headline}}</h1>
	<h4>{{post.sub_headline}}</h4>
	<br>

	<p>{{post.body|safe}}</p>

	<div class="comments-wrapper">
			{% if user.is_authenticated %}
			<form action="{% url 'LikeThisPost' post.slug %}" method="POST">
				{% csrf_token %}

				{% if user in post.likes.all %}
				<button type="submit" name="post.slug" value="{{post.slug}}"  style="background:none;border : none;"><i class="fas fa-heart " style="color:red;"></i></button>
				{% else %}
				<button type="submit" name="post.slug" value="{{post.slug}}" style="background:none;border : none;"><i class="far fa-heart" ></i></button>
				{% endif %}
			</form>
			{% else %}
			<button type="submit" name="post.slug" value="{{post.slug}}" style="background:none;border : none;"> <a  href="{% url 'login' %}?next={{request.path}}"><i class="far fa-heart" ></i></a></button>
			{% comment %} <a class="btn btn-outline-info" href="{% url 'login' %}?next={{request.path}}">Log in to like this article!</a><br> {% endcomment %}
			{% endif %}
		<h6>Like: {{post.likes.all.count}}</h6>
		<h6>Comments: {{post.postcomment_set.all.count}}</h6>
		<h6>Created at: {{post.created|date:"H:i:s | d-m-Y"}}</h6>
		<hr>
		<!--
			- Not logged in, output form and say "Register to comment and give room for a message"
			- When given username 
		-->
		{% if request.user.is_authenticated %}
		<form action="" method="POST">
			{% csrf_token %}
			<textarea required class="form-control" placeholder="Leave a comment..." name="comment"></textarea>
			<br>
			<input class="btn btn-info" type="submit" value="Submit">
		</form>
		{% else %}
			<p>Create an account to comment:</p>
			<a class="btn btn-primary" href="{% url 'register' %}">Register/Login</a>
		{% endif %}

		<hr>
		{% for comment in post.postcomment_set.all %}
			<div  class="comment">
				<img class="author-pic" src="{{comment.author.profile_pic.url}}">
				
					<div>
						<p class="comment-author">{{comment.author}}: {{comment.created|date:"H:i:s | d-m-Y"}}</p>
					<div class="comment-span">
						<span class="comment-body">{{comment.body}}</span>
					</div>
					</div>
			</div>
		{% endfor %}
	</div>
</div>

{% endblock content %}

VyHung/base/templates/base/post_form.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
   <div class="main-container" style="padding :20px;">
	<a class="btn btn-sm btn-primary" href="{% url 'posts' %}">&laquo Back to Posts</a>
	
	<form action="" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form.media}}
		{{form | crispy}}
	
		<input class="btn btn-primary" type="submit" value="Submit Post">
		
	</form>
</div>
{% endblock content %}

VyHung/base/templates/base/posts.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<style type="text/css">
body{
		background-image: var(--background-image);
	}
	
</style>

	<div class= "main-container" >
	<h1>Post</h1>
	{% if request.user.is_staff %}
		<a class="btn btn-primary" href="{% url 'create_post' %}">Create Post</a>
	{% endif %}
	<form style="font-family: 'Roboto Mono', monospace;margin-bottom: 12px; " id="searchForm" method="GET">
		{{myFilter.form | crispy}}
		<input class="btn btn-primary" type="submit"  value="Search">
	
	
	</form>

		<div class="post-wrapper">
			{% for post in posts %}
			<div>
				<div class="post">
					<img class="thumbnail" src="{{post.thumbnail.url}}">
					<div style="padding : 12px">
						<h6 class="post-title">{{post.headline}}</h6>
						<p class="post-intro">{{post.sub_headline}}</p>
						<a href="{% url 'post' post.slug %}">More</a>

						{% if request.user.is_staff %}
						| <a href="{% url 'update_post' post.slug %}">Edit</a>
						| <a href="{% url 'delete_post' post.slug %}">Delete</a>
						{% endif %}

						<hr>
						{% for tag in post.tags.all %}
							<span class="tag">{{tag}}</span>
						{% endfor %}
						<hr>
						<div class="w-75 d-flex  justify-content-start">

							{% comment %} tes/ {% endcomment %}
							{% if user.is_authenticated %}
							<form action="{% url 'postLike' post.slug %}" method="POST">
								{% csrf_token %}

								{% if user in post.likes.all %}
								<button type="submit" name="post.slug" value="{{post.slug}}"  style="background:none;border : none;"><i class="fas fa-heart " style="color:red;"></i></button>
								{% else %}
								<button type="submit" name="post.slug" value="{{post.slug}}" style="background:none;border : none;"><i class="far fa-heart" ></i></button>
								{% endif %}
							</form>
							{% else %}
							<button type="submit" name="post.slug" value="{{post.slug}}" style="background:none;border : none;"> <a  href="{% url 'login' %}?next={{request.path}}"><i class="far fa-heart" ></i></a></button>
							{% comment %} <a class="btn btn-outline-info" href="{% url 'login' %}?next={{request.path}}">Log in to like this article!</a><br> {% endcomment %}
							{% endif %}
							
							{% comment %} test {% endcomment %}
							

							<div style="margin:0px 20px 0 0px;">{{post.likes.all.count}}</div>
							<a style="text-decoration: none;margin-right: 2px;"  href="{% url 'post' post.slug %}"><i class="far fa-comments"></i></a>
							<div >{{post.postcomment_set.all.count}}</div>
							
              			</div>
					</div>
				</div>
			</div>
			{% empty %}
				<h3>No posts found...</h3>
			{% endfor %}
		</div>

	<div class="row d-flex justify-content-center">
		
		{% if posts.has_other_pages %}

			<ul class="pagination">

				{% if posts.has_previous %}
					<li class="page-item"><a data-page="{{posts.previous_page_number}}" href="?page={{posts.previous_page_number}}" class="page-link">&laquo</a></li>

					<li class="page-item"><a data-page="1" href="?page=1" class="page-link">First</a></li>
				{% endif %}


				{% for i in posts.paginator.page_range %}
					{% if posts.number == i %}
						<li class="page-item"><a class="active page-link">{{i}}</a></li>
					{% else %}
						<li class="page-item"><a data-page="{{i}}" href="?page={{i}}" class="page-link">{{i}}</a></li>
					{% endif %}
					
				{% endfor %}


				{% if posts.has_next %}
					<li class="page-item"><a data-page="{{posts.paginator.num_pages}}" href="?page={{posts.paginator.num_pages}}" class="page-link">Last</a></li>

					<li class="page-item"><a data-page="{{posts.next_page_number}}" href="?page={{posts.next_page_number}}" class="page-link">&raquo</a></li>
				{% endif %}
			</ul>

		{% endif %}
	</div>

	</div>

<script type="text/javascript">
	let searchForm = document.getElementById('searchForm')
	let pageLinks = document.getElementsByClassName('page-link')

	for(var i=0; pageLinks.length > i; i++){

		pageLinks[i].addEventListener('click', function(e){
			e.preventDefault()
			let page = this.dataset.page
			console.log('Page:', page)
			searchForm.innerHTML += `<input value="${page}" name="page" hidden >`
			searchForm.submit()
		})

	}
</script>



{% endblock content %}

VyHung/base/templates/base/profile.html
{ en

VyHung/base/templates/base/profile_form.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="main-container">
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form|crispy}}
		<input class="btn btn-primary" type="submit" value="Save">
	</form>
</div>
{% endblock content %}